steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build'
  args: 
  - 'build'
  - '-f'
  - 'Profile/Dockerfile'
  - '-t'
  - 'gcr.io/$PROJECT_ID/profile:$COMMIT_SHA'
  -  '.'
  timeout: 900s

- name: 'gcr.io/cloud-builders/docker'
  id: push
  args: 
  - 'push'
  - 'gcr.io/$PROJECT_ID/profile:$COMMIT_SHA'

- name: 'gcr.io/cloud-builders/kubectl'
  id: apply
  args: 
  - 'apply'
  - '-f'
  - 'deploy/'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cpulse'
  
- name: 'gcr.io/cloud-builders/kubectl'
  id: set-image
  args: 
  - 'set'
  - 'image'
  - 'deployment/profile'
  - 'cpulse=gcr.io/$PROJECT_ID/profile:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=profile'
timeout: 900s
